export const projectTemplate = {
  id: undefined,
  client: undefined,
  contractor: "Pixelogic Media",
  date_assigned: undefined,
  date_due: undefined,
  episode: undefined,
  hourly_rate: undefined,
  invoice_amount: undefined,
  rate: 6,
  runtime: undefined,
  title: undefined,
  work_time: 0,
  workplace_url: "",
};
