export const projectTemplate = {
  id: undefined,
  client: undefined,
  contractor: "Pixelogic Media",
  date_assigned: undefined,
  date_due: undefined,
  episode: undefined,
  hourly_rate: undefined,
  invoice_amount: undefined,
  rate: 6,
  runtime: undefined,
  title: undefined,
  work_time: undefined,
  workplace_url: undefined,
};

export const PROJECT_FIELDS = [
  "id",
  "client",
  "contractor",
  "date_assigned",
  "date_due",
  "episode",
  "hourly_rate",
  "invoice_amount",
  "rate",
  "runtime",
  "title",
  "work_time",
  "workplace_url",
];
