const testAssignments = [
  {
    alpha_clients: "Disney",
    alpha_id: 192168,
    alpha_name: "Broadcast_Original",
    alpha_source_materials: [],
    assignee_id: 8587,
    assignee_name: "John Gray",
    assignee_type: "Individual",
    assignment_id: 20395845,
    billable: true,
    configuration_name: "Audio Description",
    contact_first_name: null,
    contact_full_name: null,
    contact_id: null,
    contact_last_name: null,
    content_spec: null,
    created_at: "2025-11-20T11:12:06.633Z",
    due_date: "2025-12-16T07:59:00.000Z",
    episode_name: "Episode 1",
    episode_number: "E0001",
    file_variants: [null],
    hide_approve: true,
    instructions: "",
    is_template_configuration: false,
    job_group: "Audio Description",
    job_id: 2577539,
    language_id: 18,
    language_name: "English (US)",
    localization_assignment_main_type_name: "scripting_dialogue",
    localization_assignment_type_id: 24,
    localization_assignment_type_name: "Dialogue",
    localization_job_type: "Origination",
    master_file_variant_index: 4,
    master_script_edits_pending_export: true,
    milestone: "Creation In Progress",
    notes:
      "Please create English AD Template script for mastering deliverable. Thank you!",
    parent_jobs: [null, null, null],
    post_processing_notes: null,
    proxy_type: "Proxy - Texted",
    proxy_version: 1,
    qc_type: null,
    recid: 20395845,
    reference_materials_count: 3,
    service_type: "Scripting",
    status: "open",
    subtitle_file_auto_qc_result: null,
    title: "Betrayal: Secrets and Lies: Season 1: Episode 1: Episode 1 (E0001)",
    title_type: 1,
    total: 1,
    translation_count: 1,
    user_email: null,
    user_id: null,
    vendor_location_name: null,
  },
  {
    alpha_clients: "Netflix",
    alpha_id: 183492,
    alpha_name: "Streaming_International",
    alpha_source_materials: [],
    assignee_id: 7234,
    assignee_name: "Sarah Martinez",
    assignee_type: "Individual",
    assignment_id: 20395912,
    billable: true,
    configuration_name: "Subtitling",
    contact_first_name: null,
    contact_full_name: null,
    contact_id: null,
    contact_last_name: null,
    content_spec: null,
    created_at: "2025-11-22T14:30:22.148Z",
    due_date: "2025-12-20T23:59:00.000Z",
    episode_name: "Episode 5",
    episode_number: "E0005",
    file_variants: [null],
    hide_approve: false,
    instructions: "Standard Netflix timing guidelines apply",
    is_template_configuration: false,
    job_group: "Subtitling",
    job_id: 2578103,
    language_id: 42,
    language_name: "Spanish (Spain)",
    localization_assignment_main_type_name: "translation_subtitle",
    localization_assignment_type_id: 12,
    localization_assignment_type_name: "Full Translation",
    localization_job_type: "Translation",
    master_file_variant_index: 2,
    master_script_edits_pending_export: false,
    milestone: "Translation In Progress",
    notes: "Rush job - client needs by end of week",
    parent_jobs: [null, null, null],
    post_processing_notes: null,
    proxy_type: "Proxy - Clean",
    proxy_version: 2,
    qc_type: "Standard",
    recid: 20395912,
    reference_materials_count: 7,
    service_type: "Translation",
    status: "in_progress",
    subtitle_file_auto_qc_result: "passed",
    title: "Midnight Chronicles: Season 2: Episode 5: The Awakening (E0005)",
    title_type: 2,
    total: 1,
    translation_count: 3,
    user_email: null,
    user_id: null,
    vendor_location_name: "Madrid Office",
  },
];
